site_name: Cascade model
nav:
    - 'index.md'
    - 'inputs_outputs.md'
    - 'running.md'
    - 'scaling.md'
    - 'tests.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  plugins:
    - search
    - tables
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
